<a href="https://colab.research.google.com/github/Sanket71/ANN/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Artificial Neural Network**

Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

Part-01 Data Preprocessing

Importing the dataset

In [ ]:
tf.__version__

'2.18.0'

In [ ]:
dataset=pd.read_csv('Churn_Modelling.csv')
print(dataset)
print(dataset.shape)
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

      RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMemb

In [ ]:
print(X.shape)

(10000, 10)


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


**Encoding categorical data**

**Label Encoding the "Gender" Column**

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])
print(X[:,2])
print(X)

[0 0 0 ... 0 1 0]
[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" Column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))
print(X[:,1])

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Splitting the datset into the training set and test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

**Part 2 Building the ANN**

Initializing the ANN

In [ ]:
ann=tf.keras.models.Sequential()

Adding the input layer and first hidden layer

In [ ]:
ann = tf.keras.Sequential([
    tf.keras.Input(shape=(12,)),
    tf.keras.layers.Dense(units=6, activation='relu')
])

Adding second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Adding output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

**Part 3 Training the ANN**

In [ ]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

**Training the ANN on the Training set**

In [ ]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5937 - loss: 0.7276
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7847 - loss: 0.5347
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8052 - loss: 0.4669
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7959 - loss: 0.4536
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8116 - loss: 0.4364
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8238 - loss: 0.4198
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8246 - loss: 0.4197
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8224 - loss: 0.4111
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8324 - loss: 0.3967
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8251 - loss: 0.4081
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8403 - loss: 0.3823
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━

**Part 4 -Making the predictions and evaluating the model**

Predicting the result of a single observation :  
Geography:France  
Credit score:600  
Gender:male  
Age:40 year  
Tenure:3 year  
Balance: $60000  
Number of product:2  
Does this customer have a credit card? : yes  
is this customer an Active Member:yes  

Estimated Salary:$50000  
so,should we say goodbye to that customer?

In [ ]:
transformed_input=sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])

prediction=ann.predict(transformed_input)

predicted_class=prediction>0.5

print(prediction)
print(predicted_class)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
[[0.03842573]]
[[False]]


Therefore,our ANN model predicts that this customer stays in the bank!  
**Important Note 1** : Notice that the values of the features were all input in a double pair of square brackets. That's because the 'predict method always expects a 2D arrays as the format of its input.And putting our values into a double pair of square brackets makes the input exactly a 2D array.  
**Important Note 2** : Notice also that the'France' country was not input as a string in the last column but as "1,0,0" in the first three columns.That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X,"France" was encoded as "1,0,0".And be careful to include these values into three columns,because the dummy variables are always created in the first columns.

Predecting the TEST set results

In [ ]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making the confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1525   70]
 [ 207  198]]


0.8615